[build-system]
requires = ["maturin>=1,<2"]
build-backend = "maturin"

[project]
name = "sysand-cli"
description = "A package manager for SysML v2 and KerML"
license = "MIT OR Apache-2.0"
dynamic = ["version"]
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Rust"
]
# TODO: create a proper readme and/or docs to document what is available
readme = "README.md"
maintainers = [
    { name = "Sensmetry", email = "opensource@sensmetry.com" }
]

[project.urls]
documentation = "https://docs.sysand.org"
homepage = "https://beta.sysand.org"
source = "https://github.com/sensmetry/sysand"
issues = "https://github.com/sensmetry/sysand/issues"

[tool.maturin]
bindings = "bin"
strip = true
